### PR TITLE
Report CSV (Issue #5)

### PR DESCRIPTION
**Pull request by ndgnuh**
Basically this it works, the current output looks like this:
image

The data used to aggregate is the same as the one used for plotting. Right now there are some code overlap. TODO:

- [x] Generate a pandas.DataFrame to report on the data.
- [ ] Clean up code
  - [ ] Make the gather function collect DataFrame instead of just the `np.array` (for potential simulation output change)
  - [ ] Make the plot function receive (DataFrame, column,...) or (pd.Series,..)
  - [ ] Rename mis-leading named functions
- [ ] Documentation

### CODE REVIEW

**Review by chapuisk — APPROVED** [review]

**Comment by chapuisk** [comment]
In fact, there is a big point missing in this report: 100k relative hospitalization, ICU, susceptible and so on.

**Comment by ndgnuh** [comment]
@chapuisk  The number is scaled, the total in the table is not the total at each step, it's the accumulated total in the whole simulation, that's why I use `max` here.
https://github.com/COMOKIT/comokit4py/blob/7762dcb340691b20582140f5b71edbabbf0c9cdc/base/post-processing/comokitreport.py#L66-L71

**Comment by chapuisk** [comment]
@ndgnuh Ok ! so now we should have each column both relative to 100k and unscaled (side by side or in different table, as u wish). This btw should be done, both here and within, what @RoiArthurB refers as "plot" part of the lib (that should definitely not be labeled like that, but this will be in another upcoming issue)

**Comment by RoiArthurB** [comment]
> his btw should be done, both here and within, what @RoiArthurB refers as "plot" part of the lib

@chapuisk How would you like to plot (graph drawing) single values ? Bar chart ? 🤔🤔🤔

**Comment by chapuisk** [comment]
> > his btw should be done, both here and within, what @RoiArthurB refers as "plot" part of the lib
> 
> @chapuisk How would you like to plot (graph drawing) single values ? Bar chart ? 🤔🤔🤔

"This" means every simulation outcome should be available as it is now AND relative to 100k 
"Not labeled like this" means that the objective should be to translate replication into a single csv with all variables, deviation, etc. And then propose to plot things relative to it 
"New issue" means add external data to plots. More to come on this asap

**Comment by ndgnuh** [comment]
Since the functionality of generating report should be the same, where regardless of scaling or not, I parameterized the scaling.

The data is **scaled to 100k by default**. If one wants to get the unscaled version simply add `scaled=False` to the parameter of `generateReport`.

**Pull request merged**
