### PR TITLE
I make it easier to add more test as we write new things.

### PR DESCRIPTION
**Pull request by ndgnuh**
## TODO

- [ ] Add test for running GAMA's simulation
- [ ] Add test for running with Slurm
- [ ] Add test for the CSV report

Not so sure about the EDF part. Do we need a test for that?

## Original PR
I need help on the launching exploration tests (especially the `slurm` test). To run the test: `python test/runtests.py`. To add tests, write test directory to the `runtests.py` or write test in a `mytestmodule.py`, eg:

```python
import comokit4py
from testfacility import test, testheader, testdir

testheader("The name of the test set")
#...
@test("Parameter combination (the name of the test)")
def _():
	# See TestExperiment.gaml
	# The variable are scaled up because python doesn't support float range
	# Basic viral release
	p1 = range(1, 11, 1)
	# Basic viral decrease
	p2 = range(2, 21, 2)
	# End of range should not be included...
	result = 11 not in p1
	spaceSize = len(p1) * len(p2)
	return result and len(explo.getExperimentSpace()) == spaceSize
```

The return value is true when the test success, there's no need for try catch it the test be cause it was wrapped in a try-catch
```python
@test("Will fail")
def _():
	1 / 0
	return False
```
will produce `[ERROR] "Test Will fail" errored: division by zero`.

If a new module is created, it need to be import in the `runtests.py`:
```python
# Import tests
import regression
import testGama
import testGamaExperiment
...
```

### CODE REVIEW

**Comment by RoiArthurB** [comment]
@ndgnuh  Is it ready to merge ?

**Comment by ndgnuh** [comment]
Not yet, 2 tests remain + github actions.

**Comment by ndgnuh** [comment]
@RoiArthurB  Can we merge this one first and leave the other tests for later? This way I can do a check on the output of the report generation.

**Review by RoiArthurB — APPROVED** [review]
Add a file name `requirements.txt` in the new test folder if you want to use some extra python packages :smiley:

**Comment by ndgnuh** [comment]
We can do that now?

**Pull request merged**
